#ifndef GLOBALS_H
#define GLOBALS_H

#define TBGE_VERSION_MAJOR 0
#define TBGE_VERSION_MINOR 1
#define TBGE_VERSION_PATCH 1

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define TBGE_VERSION \
    TOSTRING(TBGE_VERSION_MAJOR) "." TOSTRING(TBGE_VERSION_MINOR) "." TOSTRING(TBGE_VERSION_PATCH)

#endif // GLOBALS_H
